language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2/
before_install:
  - rm -R $HOME/.m2/*
  - mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -DgroupId=net.sf.lpsolve -DartifactId=lp_solve -Dversion=5.5.2 -Dpackaging=jar -DremoteRepositories=https://raw.github.com/idsia/crema/mvn-repo/
  - mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -DgroupId=ch.javasoft.polco -DartifactId=polco -Dversion=4.7.1 -Dpackaging=jar -DremoteRepositories=https://raw.github.com/idsia/crema/mvn-repo/
  - mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -DgroupId=ch.idsia -DartifactId=crema -Dversion=0.1.5 -Dpackaging=jar -DremoteRepositories=https://raw.github.com/idsia/crema/mvn-repo/